plugins:
  - rubocop-performance
AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  inherit_mode:
    merge:
      - Exclude
      - AllowedMethods
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  inherit_mode:
    merge:
      - Exclude
  Max: 30
  Enabled: false
Metrics/ModuleLength:
  inherit_mode:
    merge:
      - Exclude
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
