#!/usr/bin/env ruby
# frozen_string_literal: true

# compress a .nam nametable with NESST-compatible RLE
# inputs:
# - .nam filename
# - .rle filename

require_relative 'rle'

map_file, rle_file = ARGV

compressed_bytes = RLE.rle(File.binread(map_file).unpack('C*'))

File.binwrite(rle_file, compressed_bytes.pack('C*'))
