name: Build ROM Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install cc65 from openSUSE Build Service
      run: |
        echo 'deb http://download.opensuse.org/repositories/home:/strik/xUbuntu_22.10/ /' | sudo tee /etc/apt/sources.list.d/home:strik.list
        curl -fsSL https://download.opensuse.org/repositories/home:strik/xUbuntu_22.10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_strik.gpg > /dev/null
        sudo apt update
        sudo apt install -y cc65
    - name: Install LLVM-MOS SDK
      run: |
        wget https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz
        tar xf llvm-mos-linux.tar.xz
        sudo mv llvm-mos /opt/llvm-mos
        echo "/opt/llvm-mos/bin" >> $GITHUB_PATH
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
    - name: Configure build
      run: |
        cmake --preset=release -DCMAKE_PREFIX_PATH=/opt/llvm-mos
    - name: Build ROM
      run: |
        cmake --build build --config MinSizeRel
    - name: Verify ROM file
      run: |
        ls -la build/miroh-jr.nes
        file build/miroh-jr.nes
    - name: Upload ROM as artifact
      uses: actions/upload-artifact@v4
      with:
        name: miroh-jr.nes
        path: build/miroh-jr.nes
        retention-days: 14
